// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
    appId: '1:77297660472:web:008d9cefe0279db41caccd',
    messagingSenderId: '77297660472',
    projectId: 'fir-basic-25064',
    authDomain: 'fir-basic-25064.firebaseapp.com',
    storageBucket: 'fir-basic-25064.firebasestorage.app',
    measurementId: 'G-KC09PRNB08',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: '1:77297660472:android:f0abd66bd2aa0b0e1caccd',
    messagingSenderId: '77297660472',
    projectId: 'fir-basic-25064',
    storageBucket: 'fir-basic-25064.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:77297660472:ios:7ec9828d304d0aa41caccd',
    messagingSenderId: '77297660472',
    projectId: 'fir-basic-25064',
    storageBucket: 'fir-basic-25064.firebasestorage.app',
    iosBundleId: 'com.example.venturoCore',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS']!,
    appId: '1:77297660472:ios:7ec9828d304d0aa41caccd',
    messagingSenderId: '77297660472',
    projectId: 'fir-basic-25064',
    storageBucket: 'fir-basic-25064.firebasestorage.app',
    iosBundleId: 'com.example.venturoCore',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WINDOWS']!,
    appId: '1:77297660472:web:ce44a1ffcef76b8d1caccd',
    messagingSenderId: '77297660472',
    projectId: 'fir-basic-25064',
    authDomain: 'fir-basic-25064.firebaseapp.com',
    storageBucket: 'fir-basic-25064.firebasestorage.app',
    measurementId: 'G-3F7M7MVV2Q',
  );
}
